export const GET_CRYPTO_SUCCESS = 'GET_CRYPTO_SUCCESS'
export const GET_CRYPTO_FAILURE = 'GET_CRYPTO_FAILURE'
export const GET_CRYPTO_STARTED = 'GET_CRYPTO_STARTED'
export const GET_CRYPTO_ENDED = 'GET_CRYPTO_ENDED'

export const CHANGE_THEME = 'CHANGE_THEME'